spring.application.name=sonata-viajes

# Base de datos - PostgreSQL local
spring.datasource.url=jdbc:postgresql://localhost:5432/viajes
spring.datasource.username=postgres
spring.datasource.password=Tanque.123
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Servidor
server.port=8080

# Multipart upload
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=12MB

# JPA open-in-view
spring.jpa.open-in-view=false

# CORS
cors.allowed-origins=http://localhost:4200

# Admin
admin.username=admin
admin.password=SonataViajes2025!

# Upload local (solo para desarrollo)
app.upload.dir=uploads

# Cloudinary (solo producción — no se usa en local)
cloudinary.cloud-name=drd37bhg0
cloudinary.api-key=369781325274234
cloudinary.api-secret=iWVO8xwXsJrDxUC-c8BlDyjATZ4
