spring.application.name=sonata-viajes

# Base de datos - PostgreSQL local
spring.datasource.url=jdbc:postgresql://localhost:5432/viajes
spring.datasource.username=postgres
spring.datasource.password=Tanque.123
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Servidor
server.port=8080

# CORS
cors.allowed-origins=http://localhost:4200
